WBK/WBK/Models/Create/CreateSurveyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataModels;

namespace WBK.Models.Create
{
    public class CreateSurveyViewModel
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string StartLocationLat { get; set; }
        public string StartLocationLong { get; set; }
        public DateTime EndDate { get; set; }
    }
}

WBK/WBK/Models/Create/MultipleChoiceOptionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WBK.Models.Create
{
    public class MultipleChoiceOptionViewModel
    {
        public string Answer { get; set; }
        public string Description { get; set; }
        public string ImageUrl { get; set; }
        public bool Selected { get; set; }
    }
}

WBK/WBK/Models/Create/PageQuestionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WBK.Models.Create
{
    public class PageQuestionModel
    {
        public int PageId { get; set; }
        public int QuestionId { get; set; }
        public int OptionId { get; set; }
        public bool FirstGeoQuestionInPage { get; set; }
    }
}

WBK/WBK/Models/Create/PageViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace WBK.Models.Create
{
    public class PageViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public List<QuestionViewModel> Questions { get; set; }
        public string ImageUrl { get; set; }
    }
}

WBK/WBK/Models/Create/QuestionViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Linq;
using System.Threading.Tasks;
using DataModels;

namespace WBK.Models.Create
{
    public class QuestionViewModel
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public TypeEnum Type { get; set; }
        public CategoryEnum Category { get; set; }
        public int MaxValue { get; set; }
        public int MinValue { get; set; }
        public int SliderScaleVal { get; set; }
        public string SliderMinText { get; set; }
        public string SliderMaxText { get; set; }
        public GeoTypeEnum GeoType { get; set; }
        [DisplayName("Verplicht:")]
        public bool IsRequierd { get; set; }
        public List<MultipleChoiceOptionViewModel> Options { get; set; }
        public int MaximumNumberOfAnswers { get; set; }
        public string TextAnswer { get; set; }
        public string GeoCodeAnswer { get; set; }
        public int NumberAnswer { get; set; }
        public string Attribute { get; set; }
        public string ImageUrl { get; set; }
        public string StartLocationLat { get; set; }
        public string StartLocationLong { get; set; }
        public int StartZoomLevel { get; set; }





    }
}

WBK/WBK/Models/Create/SurveyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DataModels;

namespace WBK.Models.Create
{
    public class SurveyViewModel
    {
        public string Title { get; set; }
        public string Description { get; set; }
        public string EndDate { get; set; }
        public List<PageViewModel> PagesList { get; set; }
        public string ImageUrl { get; set; }
    }
}

WBK/WBK/Controllers/CreateController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Threading.Tasks;
using DataModels;
using DataModels.Questions;
using Logic;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using WBK.Models.Create;

namespace WBK.Controllers
{
    public class CreateController : Controller
    {
        private readonly SurveyLogic _logic = new SurveyLogic();

        [HttpGet]
        public IActionResult Survey(string title)
        {
            SurveyViewModel model;
            if (title != null)
            {
                Survey survey = _logic.GetSurvey(title);
                return View(ConvertModelToView(survey));
            }
            else
            {
                model = new SurveyViewModel { PagesList = CreateEmptyPageModel() };
                return View(model);
            }
            
        }

        [HttpPost]
        public IActionResult Survey(SurveyViewModel model)
        {

            _logic.InsertSurvey(ConvertViewToModel(model));
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpGet]
        public IActionResult EditSurvey(string title)
        {
            Survey survey = _logic.GetSurvey(title);
            SurveyViewModel model = ConvertModelToView(survey);
            return View(model);
        }

        [HttpPost]
        public IActionResult EditSurvey(SurveyViewModel model)
        {
            Survey surveyToUpdate = ConvertViewToModel(model);
            _logic.UpdateSurvey(surveyToUpdate);
            return RedirectToAction("Index", "Dashboard");
        }

        [HttpGet]
        public IActionResult DeleteSurvey(string title)
        {
            _logic.DeleteSurvey(HttpContext.Session.GetString("Email"), title);
            return RedirectToAction("Index", "Dashboard");
        }

        private List<PageViewModel> CreateEmptyPageModel()
        {
            List<PageViewModel> model = new List<PageViewModel>();
            model.Add(new PageViewModel());
            model[0].Questions = new List<QuestionViewModel>();
            model[0].Questions.Add(new QuestionViewModel());
            model[0].Questions[0].Options = new List<MultipleChoiceOptionViewModel>();
            model[0].Questions[0].Options.Add(new MultipleChoiceOptionViewModel());
            return model;
        }

        private Survey ConvertViewToModel(SurveyViewModel model)
        {
            Survey surveyModel = new Survey
            {
                Title = model.Title,
                Description = model.Description,
                Owner = HttpContext.Session.GetString("Email"),
                EndDate = DateTime.Parse(model.EndDate, CultureInfo.CreateSpecificCulture("nl-NL")),
                DateOfCreation = DateTime.Today,
                ImageUrl = model.ImageUrl
            };

            List<Page> pages = new List<Page>();
            foreach (PageViewModel pageView in model.PagesList)
            {
                Page page = new Page
                {
                    Id = pageView.Id,
                    Title = pageView.Title,
                    Description = pageView.Description,
                    Questions = new List<Question>(),
                    ImageUrl = pageView.ImageUrl

                };
                if (pageView.Questions != null)
                {
                    foreach (QuestionViewModel questionView in pageView.Questions)
                    {
                        questionView.Category = CategoryEnum.Algemeen;

                        switch (questionView.Type)
                        {
                            case TypeEnum.GeoVraag:

                                GeoQuestion geoQuestion = new GeoQuestion
                                {
                                    Id = questionView.Id,
                                    Value = questionView.Title,
                                    Description = questionView.Description,
                                    IsRequired = questionView.IsRequierd,
                                    Category = questionView.Category,
                                    Type = questionView.Type,
                                    ImageUrl = questionView.ImageUrl,
                                    TypeOfMarker = questionView.GeoType,
                                    StartLocation = null,
                                    Attribute = questionView.Attribute
                                };

                                if (!string.IsNullOrEmpty(questionView.StartLocationLat))
                                {
                                    Location startLocation = new Location(Convert.ToDouble(questionView.StartLocationLat.Replace('.', ',')), Convert.ToDouble(questionView.StartLocationLong.Replace('.', ',')), questionView.StartZoomLevel);
                                    geoQuestion.StartLocation = startLocation;
                                }
                                page.Questions.Add(geoQuestion);
                                break;

                            case TypeEnum.OpenVraag:
                                OpenQuestion openQuestion = new OpenQuestion
                                {
                                    Value = questionView.Title,
                                    Id = questionView.Id,
                                    Description = questionView.Description,
                                    IsRequired = questionView.IsRequierd,
                                    Category = questionView.Category,
                                    ImageUrl = questionView.ImageUrl,
                                    Type = questionView.Type,
                                    Attribute = questionView.Attribute
                                };
                                page.Questions.Add(openQuestion);
                                break;

                            case TypeEnum.NummerVraag:
                                NumberQuestion numberQuestion = new NumberQuestion
                                {
                                    Value = questionView.Title,
                                    Id = questionView.Id,
                                    Description = questionView.Description,
                                    IsRequired = questionView.IsRequierd,
                                    Category = questionView.Category,
                                    Type = questionView.Type,
                                    ImageUrl = questionView.ImageUrl,
                                    Maximum = questionView.MaxValue,
                                    Minimum = questionView.MinValue,
                                    Attribute = questionView.Attribute
                                };
                                page.Questions.Add(numberQuestion);
                                break;

                            case TypeEnum.SliderVraag:
                                SliderQuestion sliderQuestion = new SliderQuestion
                                {
                                    Value = questionView.Title,
                                    Id = questionView.Id,
                                    Description = questionView.Description,
                                    IsRequired = questionView.IsRequierd,
                                    Category = questionView.Category,
                                    Type = questionView.Type,
                                    ImageUrl = questionView.ImageUrl,
                                    MaxValueText = questionView.SliderMaxText,
                                    MinValueText = questionView.SliderMinText,
                                    Scale = questionView.SliderScaleVal,
                                    Attribute = questionView.Attribute
                                };
                                page.Questions.Add(sliderQuestion);
                                break;

                            case TypeEnum.MeerkeuzeVraag:
                                MultipleChoiceQuestion multipleChoiceQuestion = new MultipleChoiceQuestion
                                {
                                    Value = questionView.Title,
                                    Id = questionView.Id,
                                    Description = questionView.Description,
                                    IsRequired = questionView.IsRequierd,
                                    Category = questionView.Category,
                                    Type = questionView.Type,
                                    ImageUrl = questionView.ImageUrl,
                                    MaximumNumberOfAnswers = questionView.MaximumNumberOfAnswers,
                                    Options = new List<MultipleChoiceOption>(),
                                    Attribute = questionView.Attribute
                                };
                                foreach (MultipleChoiceOptionViewModel optionView in questionView.Options)
                                {
                                    MultipleChoiceOption option = new MultipleChoiceOption(optionView.Answer, optionView.Description, optionView.ImageUrl);
                                    multipleChoiceQuestion.Options.Add(option);
                                }
                                page.Questions.Add(multipleChoiceQuestion);
                                break;
                        }
                    }

                }
                pages.Add(page);
            }

            surveyModel.Pages = pages;
            return surveyModel;
        }

        private SurveyViewModel ConvertModelToView(Survey survey)
        {
            SurveyViewModel viewModel = new SurveyViewModel
            {
                Title = survey.Title,
                Description = survey.Description,

WBK/WBK/Views/Create/EditSurvey.cshtml
@{
    Layout = "";
}

@using DataModels
@using DataModels.Questions
@using WBK.Models.Create
@model WBK.Models.Create.SurveyViewModel

<!DOCTYPE html>
<html lang="nl">
<head runat=server>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>WijkBeweegKaart</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    </environment>

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.6.0/dist/leaflet.css" />
    <script src="https://unpkg.com/leaflet@1.6.0/dist/leaflet.js"></script>
    <link href="~/css/site.css" rel="stylesheet" type="text/css" media="screen" runat="server" />
    <script src="~/lib/jquery/dist/jquery.js"></script>
    <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <script src="https://cdn-geoweb.s3.amazonaws.com/esri-leaflet/0.0.1-beta.5/esri-leaflet.js"></script>
    <script src="https://cdn-geoweb.s3.amazonaws.com/esri-leaflet-geocoder/0.0.1-beta.5/esri-leaflet-geocoder.js"></script>
    <link rel="stylesheet" type="text/css" href="https://cdn-geoweb.s3.amazonaws.com/esri-leaflet-geocoder/0.0.1-beta.5/esri-leaflet-geocoder.css">

</head>

<body class="p-0">
    <nav class="navbar navbar-light" style="background-color: #F9A11B;">
        <a class="navbar-brand" href="#">
            <img src="~/images/WijkBeweegKaart Logo.png" alt="WijkBeweegKaart" style="height: 80px; width: 360px;" />
        </a>
    </nav>
    <div class="container-fluid">
        <div class="">
            <h1>Enquête Aanmaken:</h1>
            @using (Html.BeginForm("EditSurvey", "Create", FormMethod.Post, new { @class = "row" }))
            {
                @Html.AntiForgeryToken()

                <div class="col-6 form-group" style="margin-top: 20px;">
                    <div>
                        <label>Titel:</label>
                        @Html.TextBoxFor(x => x.Title, new { @readonly = "readonly", required = "required", @class = "form-control" })
                    </div>
                    <div>
                        <label>Beschrijving:</label>
                        @Html.TextAreaFor(x => x.Description, new { rows = "10", cols = "80", @class = "form-control" })
                    </div>
                    <div>
                        <label>Foto URL:</label>
                        @Html.TextBoxFor(x => x.ImageUrl, new { @class = "form-control" })
                    </div>
                    <div>
                        <label>Eind Datum:</label>
                        @Html.TextBoxFor(model => model.EndDate, new { required = "required", @class = "form-control" })
                    </div>

                    <input type="submit" name="name" value="Pas Aan!" class="btn btn-success" />

                </div>

                <div class="col-6 form-group">
                    <h2>Pagina's en vragen:</h2>
                    <div id="InputsWrapper">
                        @for (var i = 0; i < Model.PagesList.Count(); i++)
                        {
                            <div class="pageDiv">
                                <div>
                                    <h3 style="float: left;">Pagina @(i + 1)</h3>
                                </div>
                                @Html.TextBoxFor(x => x.PagesList[i].Title, new { placeholder = "Pagina Titel", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.PagesList[i].Title)

                                @Html.TextBoxFor(x => x.PagesList[i].ImageUrl, new { placeholder = "Foto URL", @class = "form-control" })

                                @Html.TextAreaFor(x => x.PagesList[i].Description, new { placeholder = "Pagina Beschrijving", rows = "5", cols = "40", @class = "form-control" })
                                @Html.ValidationMessageFor(x => x.PagesList[i].Description)
                                
                                @Html.HiddenFor(x => x.PagesList[i].Id)

                                @Html.Label("PageCounter", i.ToString(), new { style = "display: none;" })

                                <div class="QuestionWrapper">

                                    @for (var j = 0; j < Model.PagesList[i].Questions.Count(); j++)
                                    {
                                    <div class="questionDiv" style="border-style: solid; border-color: darkorange; border-width: 3px; border-radius: 5px; padding: 5px; margin-top: 10px;">
                                        <h3 style="float: left;">Vraag @(j + 1)</h3>

                                        @Html.TextBoxFor(x => x.PagesList[i].Questions[j].Title, new { placeholder = "Vraag", required = "required", @class = "form-control" })
                                        @Html.TextBoxFor(x => x.PagesList[i].Questions[j].ImageUrl, new { placeholder = "Foto URL", @class = "form-control" })
                                        @Html.TextBoxFor(x => x.PagesList[i].Questions[j].Description, new { placeholder = "Vraag Beschrijving", @class = "form-control" })
                                        @Html.LabelFor(x => x.PagesList[i].Questions[j].IsRequierd)
                                        @Html.HiddenFor(x => x.PagesList[i].Questions[j].Id)
                                        @Html.CheckBoxFor(x => x.PagesList[i].Questions[j].IsRequierd, new { @class = "form-check-input", style = "width:100px; " })
                                        @Html.DropDownListFor(x => x.PagesList[i].Questions[j].Type, Html.GetEnumSelectList(Model.PagesList[i].Questions[j].Type.GetType()), new { @class = "form-control", @readonly = "readonly" })

                                        @Html.Label("QuestionCounter", j.ToString(), new { style = "display: none;" })

                                        <div class="question">
                                            @switch (Model.PagesList[i].Questions[j].Type)
                                            {
                                                case TypeEnum.GeoVraag:
                                                    <p>Dit is een geo vraag en daarom niet aan te passen.</p>
                                                    break;

                                                case TypeEnum.SliderVraag:
                                                    <label>Tekst aan begin slider:</label>
                                                    @Html.TextBoxFor(x => x.PagesList[i].Questions[j].SliderMinText, new { @class = "form-control" });

                                                    <label>Tekst aan eind slider:</label>
                                                    @Html.TextBoxFor(x => x.PagesList[i].Questions[j].SliderMaxText, new { @class = "form-control" });

                                                    <label>Max waarde:</label>
                                                    @Html.EditorFor(x => x.PagesList[i].Questions[j].SliderScaleVal, new { @class = "form-control" });
                                                    <p>(De begin waarde is altijd 0. Het getal dat hierboven ingevuld wordt is de maximale waarde.)</p>
                                                    break;

                                                case TypeEnum.NummerVraag:
                                                    <label>Minimum waarde</label>
                                                    @Html.EditorFor(x => x.PagesList[i].Questions[j].MinValue, new { @class = "form-control" });

                                                    <label>Maximum waarde</label>
                                                    @Html.EditorFor(x => x.PagesList[i].Questions[j].MaxValue, new { @class = "form-control" });
                                                    break;

                                                case TypeEnum.MeerkeuzeVraag:
                                                    <label style="display: inline-block;">Maximaal aantal antwoorden:</label>
                                                    <input style="display: inline-block;" class="form-control" data-val="true" id="PagesList_@(i)__Questions_@(j)__MaximumNumberOfAnswers" name="PagesList[@(i)].Questions[@j)].MaximumNumberOfAnswers" type="number" min="1" max="10" value="1" />

                                                    for (int q = 0; q < Model.PagesList[i].Questions[j].Options.Count; q++)
                                                    {
                                                        <div>
                                                            <h4 style="float: left;">Optie @(q + 1):</h4>
                                                            <input class="form-control" id="PagesList_@(i)__Questions_@(j)__Options_@(q)__Answer" name="PagesList[@(i)].Questions[@(j)].Options[@(q)].Answer" type="text" placeholder="Antwoord" value="@Model.PagesList[i].Questions[j].Options[q].Answer" />
                                                            <input class="form-control" id="PagesList_@(i)__Questions_@(j)__Options_@(q)__Description" name="PagesList[@(i)].Questions[@(j)].Options[@(q)].Description" type="text" placeholder="Beschrijving" value="@Model.PagesList[i].Questions[j].Options[q].Description" />
                                                            <input class="form-control" id="PagesList_@(i)__Questions_@(j)__Options_@(q)__ImageUrl" name="PagesList[@(i)].Questions[@(j)].Options[@(q)].ImageUrl" type="text" placeholder="Afbeedling URL" value="@Model.PagesList[i].Questions[j].Options[q].ImageUrl" />
                                                        </div>
                                                    }
                                                    break;
                                            }
                                        </div>
                                    </div>

                                    }

                                </div>

                            </div>

                        }
                    </div>

                </div>

            }

        </div>

    </div>

    <script type="text/javascript">

        $(document).ready(function () {
            $('#EndDate').datepicker({ dateFormat: "dd-mm-yy", minDate: -0 });

        });

    </script>
</body>
</html>

WBK/WBK/Views/Create/GeoQuestion.cshtml
@{
    Layout = null;
}

@model WBK.Models.Create.PageQuestionModel

@if (Model.FirstGeoQuestionInPage)
{
    <div class="geo question">
        <p>Klik op de kaart om het startpunt te bepalen.</p>
        <div id="mapid@(Model.PageId)" class="map" style="height: 400px; width: 400px;"></div>
        <p>Klik op de kaart om de waardes in te voeren!</p>
        <input class="form-control" id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__StartLocationLat" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].StartLocationLat" type="text" value="Latitude"/>
        <input class="form-control" id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__StartLocationLong" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].StartLocationLong" type="text" value="Longitude"/>
        <input class="form-control" id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__StartZoomLevel" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].StartZoomLevel" type="number"/>

        <label>Marker Type:</label>
        <select class="form-control" data-val="true" data-val-required="The GeoType field is required." id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__GeoType" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].GeoType">
            <option selected="selected" value="0">Marker</option>
            <option value="1">Lijn</option>
            <option value="2">Vlak</option>
        </select>
    </div>

    <script>
        var map@(Model.PageId) = L.map('mapid@(Model.PageId)').setView([51.47358, 5.453167], 13);
        var OpenStreetMap_Mapnik = L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            {
                maxZoom: 19,
                attribution: '&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'
            }).addTo(map@(Model.PageId));

        var marker@(Model.PageId) = L.marker();

        var searchControl@(Model.PageId) = new L.esri.Controls.Geosearch().addTo(map@(Model.PageId));
        var results@(Model.PageId) = new L.LayerGroup().addTo(map@(Model.PageId));

        function onMapClick@(Model.PageId)(e) {
            marker@(Model.PageId)
                .setLatLng(e.latlng)
                .bindPopup("You clicked the map at " + e.latlng.toString())
                .addTo(map@(Model.PageId) );
            document.getElementById("PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__StartLocationLat").value = e.latlng.lat;
            document.getElementById("PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__StartLocationLong").value = e.latlng.lng;
            document.getElementById("PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__StartZoomLevel").value = map@(Model.PageId).getZoom();
        }
        map@(Model.PageId).on('click', onMapClick@(Model.PageId));
    </script>
}
else
{
    <div class="geo question">
        <label>Marker Type:</label>
        <select class="form-control" data-val="true" data-val-required="The GeoType field is required." id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__GeoType" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].GeoType">
            <option selected="selected" value="0">Marker</option>
            <option value="1">Lijn</option>
            <option value="2">Vlak</option>
        </select>
    </div>
}

WBK/WBK/Views/Create/MultipleChoiceOption.cshtml
@{
    Layout = null;
}

@model WBK.Models.Create.PageQuestionModel
<div class="MCOption" style="margin-top: 10px;">
    <h4 style="float: left;">Optie @(Model.OptionId + 1):</h4>

    <div style="float: right;" class="dropleft show">
        <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuQuestion@(Model.QuestionId)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            =
        </a>
        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a style="color: red;" href="" class="removeMCOption">Verwijderen</a>
        </div>
    </div>
    <input class="form-control" id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__Options_@(Model.OptionId)__Answer" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].Options[@(Model.OptionId)].Answer" type="text" value="" placeholder="Antwoord" />
    <input class="form-control" id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__Options_@(Model.OptionId)__ImageUrl" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].Options[@(Model.OptionId)].ImageUrl" type="text" value="" placeholder="Foto URL" />
    <input class="form-control" id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__Options_@(Model.OptionId)__Description" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].Options[@(Model.OptionId)].Description" type="text" value="" placeholder="Beschrijving" />
    <label for="OptionCounter" style="display: none;">@(Model.OptionId)</label>

</div>

WBK/WBK/Views/Create/MultipleChoiceQuestion.cshtml
@{
    Layout = null;
}

@model WBK.Models.Create.PageQuestionModel

<div class="question">  
    <div class=mcWrapper>
        <label style="display: inline-block;">Maximaal aantal antwoorden:</label>
        <input style="display: inline-block;" class="form-control" data-val="true" data-val-required="The AllowMultipleAnswers field is required." id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__MaximumNumberOfAnswers" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].MaximumNumberOfAnswers" type="number" min="1" max="10" value="1"/>
        
        <div class="MCOption" style="margin-top: 10px;">
            <h4 style="float: left;">Optie @(Model.OptionId + 1):</h4>

            <div style="float: right;" class="dropleft show">
                <a class="btn btn-secondary dropdown-toggle" href="#" role="button" id="dropdownMenuQuestion@(Model.QuestionId)" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    =
                </a>
                <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                    <a style="color: red;" href="" class="removeMCOption">Verwijderen</a>
                </div>
            </div>
            <input class="form-control" id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__Options_@(Model.OptionId)__Answer" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].Options[@(Model.OptionId)].Answer" type="text" value="" placeholder="Antwoord" />
            <input class="form-control" id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__Options_@(Model.OptionId)__ImageUrl" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].Options[@(Model.OptionId)].ImageUrl" type="text" value="" placeholder="Foto URL" />
            <input class="form-control" id="PagesList_@(Model.PageId)__Questions_@(Model.QuestionId)__Options_@(Model.OptionId)__Description" name="PagesList[@(Model.PageId)].Questions[@(Model.QuestionId)].Options[@(Model.OptionId)].Description" type="text" value="" placeholder="Beschrijving" />
            <label for="OptionCounter" style="display: none;">@(Model.OptionId)</label>
            </div>

    </div>   

    <div class="addMCOptions">
        <a href="" class="addMCOption btn btn-info">Voeg optie toe! </a>
    </div>        
</div>